### ISSUE TITLE
Can Scalpel support both python 2 and python 3 projects?

### ISSUE THREAD

**Issue by ycaibb** [SMAT-Lab/Scalpel#124]
Hi, thank you for your efforts to build such executing projects!

I am using the call graph construction in the Scalpel to analyze a project using both python 2 and python 3. My question is, can Scalpel support analyze python 2? Thanks!

**Comment by Jarvx** [comment]
Hi, thanks for your interests. The project is built up Python's AST module. Since ASTs of Python have constantly changing. We do not intend to support Python2. 
However, you can do some simple adaptions to make it work. There will be some old language constructs to be taken into account if you re-developement.
